### ISSUE TITLE
parameter

### ISSUE THREAD

**Issue by hlp2020** [KHU-AGI/PriViLege#7]
Could you please send me the entire parameter quantity of the model and the number of trainable parameters?

**Comment by pgh2874** [comment]
Given that ViT-B and BERT-B are adopted as the backbone networks, the total number of parameters is 85,954,660. For learnable parameters, there are 85,954,660 in the base session and 79,872 in the incremental sessions, due to the partial freezing of parameters.

Let me know if you need more information!
